/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ISubscriptionService,
  ISubscriptionServiceInterface,
} from "../../interfaces/ISubscriptionService";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chain_id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "topic_0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_3",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_type",
        type: "uint256",
      },
    ],
    name: "subscribe",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "chain_id",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "_contract",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "topic_0",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_1",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_2",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "topic_3",
        type: "uint256",
      },
    ],
    name: "unsubscribe",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
] as const;

export class ISubscriptionService__factory {
  static readonly abi = _abi;
  static createInterface(): ISubscriptionServiceInterface {
    return new Interface(_abi) as ISubscriptionServiceInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ISubscriptionService {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as ISubscriptionService;
  }
}
