/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace AaveHFCallback {
  export type SubscriptionStruct = {
    agent: AddressLike;
    protectedUser: AddressLike;
    collateralAsset: AddressLike;
    threshold: BigNumberish;
    collateralAmount: BigNumberish;
    expiresAt: BigNumberish;
    active: boolean;
  };

  export type SubscriptionStructOutput = [
    agent: string,
    protectedUser: string,
    collateralAsset: string,
    threshold: bigint,
    collateralAmount: bigint,
    expiresAt: bigint,
    active: boolean
  ] & {
    agent: string;
    protectedUser: string;
    collateralAsset: string;
    threshold: bigint;
    collateralAmount: bigint;
    expiresAt: bigint;
    active: boolean;
  };
}

export interface AaveHFCallbackInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "AAVE_POOL"
      | "activeIds"
      | "activeSubscriptionCount"
      | "cancelSubscription"
      | "getActiveIds"
      | "getSubscription"
      | "nextId"
      | "owner"
      | "reactiveNetworkSender"
      | "register"
      | "runCycle"
      | "subscriptions"
      | "transferOwnership"
      | "updateReactiveNetworkSender"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CycleCompleted"
      | "HealthCheckFailed"
      | "ProtectionTriggered"
      | "SubscriptionExpired"
      | "SubscriptionRegistered"
  ): EventFragment;

  encodeFunctionData(functionFragment: "AAVE_POOL", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "activeIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "activeSubscriptionCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancelSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSubscription",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "reactiveNetworkSender",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "register",
    values: [
      AddressLike,
      AddressLike,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "runCycle", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "subscriptions",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReactiveNetworkSender",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "AAVE_POOL", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "activeIds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "activeSubscriptionCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cancelSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActiveIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSubscription",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "reactiveNetworkSender",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "runCycle", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "subscriptions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReactiveNetworkSender",
    data: BytesLike
  ): Result;
}

export namespace CycleCompletedEvent {
  export type InputTuple = [
    checked: BigNumberish,
    triggered: BigNumberish,
    expired: BigNumberish
  ];
  export type OutputTuple = [
    checked: bigint,
    triggered: bigint,
    expired: bigint
  ];
  export interface OutputObject {
    checked: bigint;
    triggered: bigint;
    expired: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HealthCheckFailedEvent {
  export type InputTuple = [id: BigNumberish, protectedUser: AddressLike];
  export type OutputTuple = [id: bigint, protectedUser: string];
  export interface OutputObject {
    id: bigint;
    protectedUser: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProtectionTriggeredEvent {
  export type InputTuple = [
    id: BigNumberish,
    protectedUser: AddressLike,
    healthFactor: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    protectedUser: string,
    healthFactor: bigint
  ];
  export interface OutputObject {
    id: bigint;
    protectedUser: string;
    healthFactor: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionExpiredEvent {
  export type InputTuple = [id: BigNumberish];
  export type OutputTuple = [id: bigint];
  export interface OutputObject {
    id: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SubscriptionRegisteredEvent {
  export type InputTuple = [
    id: BigNumberish,
    agent: AddressLike,
    protectedUser: AddressLike,
    threshold: BigNumberish,
    expiresAt: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    agent: string,
    protectedUser: string,
    threshold: bigint,
    expiresAt: bigint
  ];
  export interface OutputObject {
    id: bigint;
    agent: string;
    protectedUser: string;
    threshold: bigint;
    expiresAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AaveHFCallback extends BaseContract {
  connect(runner?: ContractRunner | null): AaveHFCallback;
  waitForDeployment(): Promise<this>;

  interface: AaveHFCallbackInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  AAVE_POOL: TypedContractMethod<[], [string], "view">;

  activeIds: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  activeSubscriptionCount: TypedContractMethod<[], [bigint], "view">;

  cancelSubscription: TypedContractMethod<
    [id: BigNumberish],
    [void],
    "nonpayable"
  >;

  getActiveIds: TypedContractMethod<[], [bigint[]], "view">;

  getSubscription: TypedContractMethod<
    [id: BigNumberish],
    [AaveHFCallback.SubscriptionStructOutput],
    "view"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  reactiveNetworkSender: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<
    [
      agent: AddressLike,
      protectedUser: AddressLike,
      collateralAsset: AddressLike,
      threshold: BigNumberish,
      collateralAmount: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  runCycle: TypedContractMethod<[], [void], "nonpayable">;

  subscriptions: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        agent: string;
        protectedUser: string;
        collateralAsset: string;
        threshold: bigint;
        collateralAmount: bigint;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateReactiveNetworkSender: TypedContractMethod<
    [newSender: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "AAVE_POOL"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "activeIds"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "activeSubscriptionCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancelSubscription"
  ): TypedContractMethod<[id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSubscription"
  ): TypedContractMethod<
    [id: BigNumberish],
    [AaveHFCallback.SubscriptionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "reactiveNetworkSender"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<
    [
      agent: AddressLike,
      protectedUser: AddressLike,
      collateralAsset: AddressLike,
      threshold: BigNumberish,
      collateralAmount: BigNumberish,
      duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "runCycle"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "subscriptions"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, string, bigint, bigint, bigint, boolean] & {
        agent: string;
        protectedUser: string;
        collateralAsset: string;
        threshold: bigint;
        collateralAmount: bigint;
        expiresAt: bigint;
        active: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateReactiveNetworkSender"
  ): TypedContractMethod<[newSender: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "CycleCompleted"
  ): TypedContractEvent<
    CycleCompletedEvent.InputTuple,
    CycleCompletedEvent.OutputTuple,
    CycleCompletedEvent.OutputObject
  >;
  getEvent(
    key: "HealthCheckFailed"
  ): TypedContractEvent<
    HealthCheckFailedEvent.InputTuple,
    HealthCheckFailedEvent.OutputTuple,
    HealthCheckFailedEvent.OutputObject
  >;
  getEvent(
    key: "ProtectionTriggered"
  ): TypedContractEvent<
    ProtectionTriggeredEvent.InputTuple,
    ProtectionTriggeredEvent.OutputTuple,
    ProtectionTriggeredEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionExpired"
  ): TypedContractEvent<
    SubscriptionExpiredEvent.InputTuple,
    SubscriptionExpiredEvent.OutputTuple,
    SubscriptionExpiredEvent.OutputObject
  >;
  getEvent(
    key: "SubscriptionRegistered"
  ): TypedContractEvent<
    SubscriptionRegisteredEvent.InputTuple,
    SubscriptionRegisteredEvent.OutputTuple,
    SubscriptionRegisteredEvent.OutputObject
  >;

  filters: {
    "CycleCompleted(uint256,uint256,uint256)": TypedContractEvent<
      CycleCompletedEvent.InputTuple,
      CycleCompletedEvent.OutputTuple,
      CycleCompletedEvent.OutputObject
    >;
    CycleCompleted: TypedContractEvent<
      CycleCompletedEvent.InputTuple,
      CycleCompletedEvent.OutputTuple,
      CycleCompletedEvent.OutputObject
    >;

    "HealthCheckFailed(uint256,address)": TypedContractEvent<
      HealthCheckFailedEvent.InputTuple,
      HealthCheckFailedEvent.OutputTuple,
      HealthCheckFailedEvent.OutputObject
    >;
    HealthCheckFailed: TypedContractEvent<
      HealthCheckFailedEvent.InputTuple,
      HealthCheckFailedEvent.OutputTuple,
      HealthCheckFailedEvent.OutputObject
    >;

    "ProtectionTriggered(uint256,address,uint256)": TypedContractEvent<
      ProtectionTriggeredEvent.InputTuple,
      ProtectionTriggeredEvent.OutputTuple,
      ProtectionTriggeredEvent.OutputObject
    >;
    ProtectionTriggered: TypedContractEvent<
      ProtectionTriggeredEvent.InputTuple,
      ProtectionTriggeredEvent.OutputTuple,
      ProtectionTriggeredEvent.OutputObject
    >;

    "SubscriptionExpired(uint256)": TypedContractEvent<
      SubscriptionExpiredEvent.InputTuple,
      SubscriptionExpiredEvent.OutputTuple,
      SubscriptionExpiredEvent.OutputObject
    >;
    SubscriptionExpired: TypedContractEvent<
      SubscriptionExpiredEvent.InputTuple,
      SubscriptionExpiredEvent.OutputTuple,
      SubscriptionExpiredEvent.OutputObject
    >;

    "SubscriptionRegistered(uint256,address,address,uint256,uint256)": TypedContractEvent<
      SubscriptionRegisteredEvent.InputTuple,
      SubscriptionRegisteredEvent.OutputTuple,
      SubscriptionRegisteredEvent.OutputObject
    >;
    SubscriptionRegistered: TypedContractEvent<
      SubscriptionRegisteredEvent.InputTuple,
      SubscriptionRegisteredEvent.OutputTuple,
      SubscriptionRegisteredEvent.OutputObject
    >;
  };
}
