/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AaveHFCallback } from "./AaveHFCallback";
export type { IAavePool } from "./IAavePool";
export type { IERC20 } from "./IERC20";
