/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IReactiveInterface extends Interface {
  getFunction(nameOrSignature: "react"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Callback"): EventFragment;

  encodeFunctionData(
    functionFragment: "react",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(functionFragment: "react", data: BytesLike): Result;
}

export namespace CallbackEvent {
  export type InputTuple = [
    chain_id: BigNumberish,
    _contract: AddressLike,
    gas_limit: BigNumberish,
    payload: BytesLike
  ];
  export type OutputTuple = [
    chain_id: bigint,
    _contract: string,
    gas_limit: bigint,
    payload: string
  ];
  export interface OutputObject {
    chain_id: bigint;
    _contract: string;
    gas_limit: bigint;
    payload: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IReactive extends BaseContract {
  connect(runner?: ContractRunner | null): IReactive;
  waitForDeployment(): Promise<this>;

  interface: IReactiveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  react: TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      topic_1: BigNumberish,
      topic_2: BigNumberish,
      topic_3: BigNumberish,
      data: BytesLike,
      block_number: BigNumberish,
      op_code: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "react"
  ): TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      topic_1: BigNumberish,
      topic_2: BigNumberish,
      topic_3: BigNumberish,
      data: BytesLike,
      block_number: BigNumberish,
      op_code: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "Callback"
  ): TypedContractEvent<
    CallbackEvent.InputTuple,
    CallbackEvent.OutputTuple,
    CallbackEvent.OutputObject
  >;

  filters: {
    "Callback(uint256,address,uint64,bytes)": TypedContractEvent<
      CallbackEvent.InputTuple,
      CallbackEvent.OutputTuple,
      CallbackEvent.OutputObject
    >;
    Callback: TypedContractEvent<
      CallbackEvent.InputTuple,
      CallbackEvent.OutputTuple,
      CallbackEvent.OutputObject
    >;
  };
}
