/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "AaveHFCallback",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveHFCallback__factory>;
    getContractFactory(
      name: "IAavePool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IAavePool__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "AaveHFReactive",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AaveHFReactive__factory>;
    getContractFactory(
      name: "IReactive",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReactive__factory>;
    getContractFactory(
      name: "ISubscriptionService",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISubscriptionService__factory>;

    getContractAt(
      name: "AaveHFCallback",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveHFCallback>;
    getContractAt(
      name: "IAavePool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IAavePool>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "AaveHFReactive",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AaveHFReactive>;
    getContractAt(
      name: "IReactive",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReactive>;
    getContractAt(
      name: "ISubscriptionService",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISubscriptionService>;

    deployContract(
      name: "AaveHFCallback",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AaveHFCallback>;
    deployContract(
      name: "IAavePool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAavePool>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AaveHFReactive",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AaveHFReactive>;
    deployContract(
      name: "IReactive",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReactive>;
    deployContract(
      name: "ISubscriptionService",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISubscriptionService>;

    deployContract(
      name: "AaveHFCallback",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AaveHFCallback>;
    deployContract(
      name: "IAavePool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IAavePool>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "AaveHFReactive",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AaveHFReactive>;
    deployContract(
      name: "IReactive",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReactive>;
    deployContract(
      name: "ISubscriptionService",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISubscriptionService>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
