/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AaveHFReactiveInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "callbackContract"
      | "callbackGasLimit"
      | "cronTicker"
      | "owner"
      | "react"
      | "withdraw"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Callback"): EventFragment;

  encodeFunctionData(
    functionFragment: "callbackContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "callbackGasLimit",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cronTicker",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "react",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "callbackContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "callbackGasLimit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cronTicker", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "react", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace CallbackEvent {
  export type InputTuple = [
    chain_id: BigNumberish,
    _contract: AddressLike,
    gas_limit: BigNumberish,
    payload: BytesLike
  ];
  export type OutputTuple = [
    chain_id: bigint,
    _contract: string,
    gas_limit: bigint,
    payload: string
  ];
  export interface OutputObject {
    chain_id: bigint;
    _contract: string;
    gas_limit: bigint;
    payload: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AaveHFReactive extends BaseContract {
  connect(runner?: ContractRunner | null): AaveHFReactive;
  waitForDeployment(): Promise<this>;

  interface: AaveHFReactiveInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  callbackContract: TypedContractMethod<[], [string], "view">;

  callbackGasLimit: TypedContractMethod<[], [bigint], "view">;

  cronTicker: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  react: TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BytesLike,
      arg7: BigNumberish,
      arg8: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  withdraw: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "callbackContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "callbackGasLimit"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cronTicker"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "react"
  ): TypedContractMethod<
    [
      chain_id: BigNumberish,
      _contract: AddressLike,
      topic_0: BigNumberish,
      arg3: BigNumberish,
      arg4: BigNumberish,
      arg5: BigNumberish,
      arg6: BytesLike,
      arg7: BigNumberish,
      arg8: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "Callback"
  ): TypedContractEvent<
    CallbackEvent.InputTuple,
    CallbackEvent.OutputTuple,
    CallbackEvent.OutputObject
  >;

  filters: {
    "Callback(uint256,address,uint64,bytes)": TypedContractEvent<
      CallbackEvent.InputTuple,
      CallbackEvent.OutputTuple,
      CallbackEvent.OutputObject
    >;
    Callback: TypedContractEvent<
      CallbackEvent.InputTuple,
      CallbackEvent.OutputTuple,
      CallbackEvent.OutputObject
    >;
  };
}
