/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as aaveHfCallbackSol from "./AaveHFCallback.sol";
export type { aaveHfCallbackSol };
export type { AaveHFReactive } from "./AaveHFReactive";
